### ISSUE TITLE
:en is not a valid locale on startup

### ISSUE THREAD

**Issue by christophe-dufour** [prograils/lit#49]
Hi Lit team,

I just try to run LIT, 

I add the gem,
I run the bundle command,
I run the bundle exec rails g lit:install

Then, I restart my app and I get this error : 
rails s
=> Booting WEBrick
=> Rails 4.1.0 application starting in development on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Notice: server is listening on all interfaces (0.0.0.0). Consider using 127.0.0.1 (--binding option)
=> Ctrl-C to shutdown server
I, [2014-09-16T10:36:23.905196 #83240]  INFO -- : initializing Lit
Exiting
/Users/christophedufour/.rvm/gems/ruby-2.1.1/gems/i18n-0.6.9/lib/i18n.rb:288:in `enforce_available_locales!': :en is not a valid locale (I18n::InvalidLocale)

It's rails 4 / ruby 2.1 app.

Do you have any idea what's going on?

Regards

**Comment by RandieM** [comment]
Hello there,

I am having the same problem with a fresh Rails 6.0.3.6 app. The only additional gem I am using is "lit".

As soon as lit is initialised, I get the error: `.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/i18n-1.8.10/lib/i18n.rb:343:in 'enforce_available_locales!': :en is not a valid locale (I18n::InvalidLocale)`.

Adding :en to the app's available locales makes the error go away, but this is not a good option for me, because my app will not be translated to English.

Any ideas?

**Comment by mlitwiniuk** [comment]
Hi @RandieM , please set your desired locale as default (as described [here](https://guides.rubyonrails.org/i18n.html#setup-the-rails-application-for-internationalization)) and check if this fixed the problem. If it will persist, please create new issue (this one has been closed... almost 7 years ago ;) )

**Comment by RandieM** [comment]
Thanks @mlitwiniuk for your swift response. I have now opened a new issue (#171) for this.
