### ISSUE TITLE
How to create array type translations?

### ISSUE THREAD

**Issue by Kulgar** [prograils/lit#53]
That's not really an issue but I just can't figure it out. 
I've already seen that LIT supports array types (such as date.day_names) with one input per day. 

I have two questions about that:
1st: How do you transform a "string key type" to an array one? Is there a way to do that?
2nd: How do you add a line in an already existing array value? (Like if I want to add a day to date.day_names - just an example)

Thanks :)
Kulgar

**Comment by mlitwiniuk** [comment]
Hi @Kulgar ,
To answer your questions:
1. I think, that the easiest way would be deleting key in lit and chaning call to that key wrom within app with proper default set. Or just adding key with array option in .yml file - this will be then imported to lit. 
2. Can you describe exactly what's yuor problem here / what's the case? Because if we would add possibility to add new options, then we should as well add possibility to remove options. But is someone (user / client, basically not developer) will delete one option from date.day_names, he would break whole application. That's why I would avoid this. But I don't know your case here - it may be so important, that we shouldd consider it in Lit.

**Comment by Kulgar** [comment]
Hi @mlitwiniuk: 

We just wanted to use YAML arrays to create options for some select fields in our forms, like: "Miss, Mister, Lady...", and "Chief, Engineer, Developer, Designer, etc.", options you frequently need to add or remove and that require translations. 

I know we could include html tags in YAML strings, but we just don't trust our customers to handle those tags correctly.

As a temporary solution we used a special character ($) between each option and we then split the string using that character, something like this: 

```ruby
<%# I replaced the translation key with corresponding string: %>
<% "Chief $ Engineer $ Developer $ Designer".split("$").each do |role| %>
  <option><%= role %></option>
<% end %>
```

YAML arrays would really be better to handle this I think.
Kulgar.

**Comment by mlitwiniuk** [comment]
@Kulgar 
I really think, that such case should be supported via db and some kind of backend if number of options can be changed by anyone beside developers. I think, that this is not the case, that should be solved by Lit.

**Comment by Kulgar** [comment]
Hmm, unfortunately I must agree with you. In fact those options were stored as "constants" inside the application (I did not do that, the ancient developer did), as Lit already stores its translations in the database I thought it would be - maybe - easier to use it to translate those options. 

But you're right, I should definitely create a model to store them. I'll close the issue. 
Thanks @mlitwiniuk !
